version: '3.3'

services:
  jenkins:
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"
    image: ignasliu/jenkins-controler-jcasc
    ports:
      - 50000:50000
      - 8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home
      # - $PWD/casc_configs:/var/jenkins_conf
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_conf
      # - JCASC_VERSION
      # - CONFIG_VERSION
      - JENKINS_RUNNER=${JENKINS_RUNNER:-jenkins}
      - JENKINS_PASSWORD=${JENKINS_PASSWORD:-SecretPasswd21}
      # - JENKINS_HOST=$HOSTNAME

  agent:
    image: ignasliu/jenkins-agent-jcasc
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size:  "20m"
        max-file: "3"
    environment:
      - JENKINS_RUNNER=${JENKINS_RUNNER:-jenkins}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker

volumes:
  jenkins_home: